name: flame_game_langaw
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flame: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/background/backyard.png
    - assets/images/moscas/agile-fly-1.png
    - assets/images/moscas/agile-fly-2.png
    - assets/images/moscas/agile-fly-dead.png
    - assets/images/moscas/drooler-fly-1.png
    - assets/images/moscas/drooler-fly-2.png
    - assets/images/moscas/drooler-fly-dead.png
    - assets/images/moscas/house-fly-1.png
    - assets/images/moscas/house-fly-2.png
    - assets/images/moscas/house-fly-dead.png
    - assets/images/moscas/hungry-fly-1.png
    - assets/images/moscas/hungry-fly-2.png
    - assets/images/moscas/hungry-fly-dead.png
    - assets/images/moscas/macho-fly-1.png
    - assets/images/moscas/macho-fly-2.png
    - assets/images/moscas/macho-fly-dead.png
